# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuTeHoiDongQuanTri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuTeHoiDongQuanTri
  
  # Networking
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'ReachabilitySwift'
  
  # Firebase SDK
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  
  # Google SDK
  pod 'GoogleSignIn'
  
  # Support
  pod 'lottie-ios'
  pod 'SnapKit'
  pod 'IGListKit'
  pod 'SkeletonView'
  
end

target 'StreamingTienPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StreamingTienPro

end
