# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuTeHoiDongQuanTri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuTeHoiDongQuanTri
  pod 'Kingfisher'
	pod 'Alamofire'

end

target 'StreamingTienPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StreamingTienPro

end
